### ISSUE TITLE
Generalize Static Word Embeddings and Machine Learning models to more models.

### ISSUE THREAD

**Issue by jpelhaW** [jpelhaW/NLP-Trafficking-10k#12]
The same functionality for training and evaluation that is implemented with fasttext and logistic regression should be implemented for more embedding models and machine learning classifiers.
We might change the repo code to the [flair library](https://github.com/flairNLP/flair) to make sure it is standardized.

Embeddings:
- [x] Word2Vec
- [ ] Doc2Vec

ML classifiers:
- [ ] SVM
- [ ] Naive Bayes

**Comment by HardikArora17** [comment]
Hi Jan,
I made a pull request related to word2vec and Elmo embeddings (using flair)  . Can you please check and tell me if this is exactly how the codes are to be submitted? So that I can make the commits for the remaining models by tomorrow.
